# Generated by Django 4.2.4 on 2023-08-28 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_groups', '0002_rename_owner_group_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='like_post',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like_post',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='like_post',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='group',
            name='chat_profile',
            field=models.ImageField(upload_to='group_chat_profile/%h'),
        ),
        migrations.CreateModel(
            name='ReplyLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_message', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.reply')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_message', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.comment')),
            ],
        ),
    ]
