# Generated by Django 4.2.4 on 2023-08-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelpost',
            name='likes',
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='channel_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/ch/user_post/%m%d%y'),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='channel_video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/ch/user_post/%m%d%y'),
        ),
    ]
