# Generated by Django 4.2.4 on 2023-08-24 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='channel_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/ch/user_<built-in method capitalize of str object at 0x0000011A70DA2B00>/%m%d%y'),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
