# Generated by Django 4.2.4 on 2023-08-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_channels', '0002_channel_updated_at_alter_channel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='member',
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='channel_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/ch/user_<built-in method capitalize of str object at 0x000001064D1A2AB0>/%m%d%y'),
        ),
        migrations.CreateModel(
            name='ChannelMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='user_channels.channel')),
                ('member', models.ManyToManyField(related_name='multiple_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
