# Generated by Django 4.2.4 on 2023-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0002_remove_channelpost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelprofile',
            name='chat_profile',
            field=models.ImageField(upload_to='chat_profile/%h'),
        ),
    ]
