# Generated by Django 4.2.4 on 2023-08-24 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_channels', '0003_remove_channel_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='member',
            field=models.ManyToManyField(related_name='multiple_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='channel_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/ch/user_<built-in method capitalize of str object at 0x0000022E456B2B00>/%m%d%y'),
        ),
        migrations.DeleteModel(
            name='ChannelMembers',
        ),
    ]
